services:
  db:
    image: bitnami/postgresql:latest
    env_file:
      - .env
    ports:
      - '5432'

  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    entrypoint: ./entrypoint.sh

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    command: yarn start